# Generated by Django 4.0.3 on 2022-03-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
